# Cross-language compatibility: read fixtures generated by Python zarr
#
# Fixtures are generated by: uv run test/fixtures/generate_python.py
# The Python script must be run before these tests.

using Test
using Zarrs

const FIXTURES_V3 = joinpath(@__DIR__, "fixtures", "v3_python")
const FIXTURES_V2 = joinpath(@__DIR__, "fixtures", "v2_python")

# Reference data matching what Python writes.
#
# Python creates np.arange(N).reshape(shape) in C order (row-major).
# zarrs handles the C↔column-major conversion via dimension reversal.
# In Julia, reshape(0:N-1, shape) in column-major gives the same element
# layout after zarrs's dimension reversal, because:
#   Python C-order [i,j] = i*ncols + j
#   Julia col-major [i,j] = j*nrows + i  (but with reversed dims from zarrs)
#   Net effect: Julia sees reshape(0:N-1, shape) directly.

@testset "Python zarr V3 compatibility" begin
    if !isdir(FIXTURES_V3)
        @warn "V3 Python fixtures not found at $FIXTURES_V3 — run: uv run test/fixtures/generate_python.py"
        @test_skip true
    else
        @testset "compressor: $name" for name in ["none", "zstd", "gzip", "blosc"]
            path = joinpath(FIXTURES_V3, "array_$(name).zarr")
            z = zopen(path)
            @test size(z) == (10, 10)
            @test eltype(z) == Float32
            expected = Float32.(reshape(0:99, 10, 10))
            @test z[:, :] ≈ expected
        end

        @testset "dtype: $name" for (name, T, ref_data) in [
            ("bool",       Bool,       Bool[true false; false true]),
            ("int8",       Int8,       Int8.(reshape(0:3, 2, 2))),
            ("int16",      Int16,      Int16.(reshape(0:3, 2, 2))),
            ("int32",      Int32,      Int32.(reshape(0:3, 2, 2))),
            ("int64",      Int64,      Int64.(reshape(0:3, 2, 2))),
            ("uint8",      UInt8,      UInt8.(reshape(0:3, 2, 2))),
            ("uint16",     UInt16,     UInt16.(reshape(0:3, 2, 2))),
            ("uint32",     UInt32,     UInt32.(reshape(0:3, 2, 2))),
            ("uint64",     UInt64,     UInt64.(reshape(0:3, 2, 2))),
            ("float32",    Float32,    Float32[1.5 3.5; 2.5 4.5]),
            ("float64",    Float64,    Float64[1.5 3.5; 2.5 4.5]),
            ("complex64",  ComplexF32, ComplexF32[1+2im 5+6im; 3+4im 7+8im]),
            ("complex128", ComplexF64, ComplexF64[1+2im 5+6im; 3+4im 7+8im]),
        ]
            path = joinpath(FIXTURES_V3, "dtype_$(name).zarr")
            if !isdir(path)
                @test_skip "fixture not found: $path"
                continue
            end
            z = zopen(path)
            @test eltype(z) == T
            result = z[ntuple(_ -> Colon(), ndims(z))...]
            @test result == ref_data
        end

        @testset "1D array" begin
            path = joinpath(FIXTURES_V3, "array_1d.zarr")
            z = zopen(path)
            @test size(z) == (20,)
            @test eltype(z) == Int32
            @test z[:] == Int32.(0:19)
        end

        @testset "3D array" begin
            path = joinpath(FIXTURES_V3, "array_3d.zarr")
            z = zopen(path)
            @test size(z) == (5, 4, 3)
            @test eltype(z) == Float64
            # Python: np.arange(60).reshape(3,4,5) in C order
            # zarrs reverses dims: Julia shape = (5,4,3)
            # The element layout after reversal matches reshape(0:59, 5, 4, 3)
            expected = Float64.(reshape(0:59, 5, 4, 3))
            @test z[:, :, :] ≈ expected
        end

        @testset "sharded array" begin
            path = joinpath(FIXTURES_V3, "array_sharded.zarr")
            z = zopen(path)
            @test size(z) == (10, 10)
            expected = Float32.(reshape(0:99, 10, 10))
            @test z[:, :] ≈ expected
        end

        @testset "sharded multi-chunk" begin
            path = joinpath(FIXTURES_V3, "array_sharded_multi.zarr")
            z = zopen(path)
            @test size(z) == (10, 10)
            expected = Float32.(reshape(0:99, 10, 10))
            @test z[:, :] ≈ expected
        end

        @testset "attributes" begin
            path = joinpath(FIXTURES_V3, "array_attrs.zarr")
            z = zopen(path)
            attrs = get_attributes(z)
            @test attrs["units"] == "kelvin"
            @test attrs["long_name"] == "temperature"
        end

        @testset "dimension names" begin
            path = joinpath(FIXTURES_V3, "array_dimnames.zarr")
            z = zopen(path)
            @test dimnames(z) == ("x", "y")
        end

        @testset "NaN fill value" begin
            path = joinpath(FIXTURES_V3, "array_nan_fill.zarr")
            z = zopen(path)
            @test size(z) == (4, 4)
            @test all(isnan, z[:, :])
        end
    end
end

@testset "Python zarr V2 compatibility" begin
    if !isdir(FIXTURES_V2)
        @warn "V2 Python fixtures not found at $FIXTURES_V2 — run: uv run test/fixtures/generate_python.py"
        @test_skip true
    else
        expected = Float32.(reshape(0:99, 10, 10))

        @testset "compressor: $name" for name in ["none", "zstd", "blosc"]
            path = joinpath(FIXTURES_V2, "array_$(name).zarr")
            z = zopen(path)
            @test size(z) == (10, 10)
            @test eltype(z) == Float32
            @test z[:, :] ≈ expected
        end

        @testset "1D V2 array" begin
            path = joinpath(FIXTURES_V2, "array_1d.zarr")
            z = zopen(path)
            @test size(z) == (20,)
            @test z[:] == Int32.(0:19)
        end
    end
end
