# Cross-language compatibility: read V2 fixtures generated by Zarr.jl
#
# Zarr.jl is not a dependency — fixtures must be pre-generated:
#   julia --project=../../Zarr.jl test/fixtures/generate_zarr_jl.jl

using Test
using Zarrs

const ZARR_JL_FIXTURES = joinpath(@__DIR__, "fixtures", "v2_zarr_jl")

@testset "Zarr.jl V2 compatibility" begin
    if !isdir(ZARR_JL_FIXTURES)
        @info "Zarr.jl fixtures not found at $ZARR_JL_FIXTURES — skipping"
        @test_skip true
    else
        expected_f32 = Float32.(reshape(0:99, 10, 10))

        @testset "compressor: $name" for name in ["blosc", "zstd", "none"]
            path = joinpath(ZARR_JL_FIXTURES, "array_$(name).zarr")
            z = zopen(path)
            @test size(z) == (10, 10)
            @test eltype(z) == Float32
            @test z[:, :] ≈ expected_f32
        end

        @testset "dtype: $name" for (name, T, ref_data) in [
            ("int8",    Int8,    Int8.(reshape(0:3, 2, 2))),
            ("int16",   Int16,   Int16.(reshape(0:3, 2, 2))),
            ("int32",   Int32,   Int32.(reshape(0:3, 2, 2))),
            ("int64",   Int64,   Int64.(reshape(0:3, 2, 2))),
            ("uint8",   UInt8,   UInt8.(reshape(0:3, 2, 2))),
            ("uint16",  UInt16,  UInt16.(reshape(0:3, 2, 2))),
            ("uint32",  UInt32,  UInt32.(reshape(0:3, 2, 2))),
            ("uint64",  UInt64,  UInt64.(reshape(0:3, 2, 2))),
            ("float32", Float32, Float32[1.5 3.5; 2.5 4.5]),
            ("float64", Float64, Float64[1.5 3.5; 2.5 4.5]),
        ]
            path = joinpath(ZARR_JL_FIXTURES, "dtype_$(name).zarr")
            z = zopen(path)
            @test eltype(z) == T
            @test z[ntuple(_ -> Colon(), ndims(z))...] == ref_data
        end

        @testset "1D array" begin
            path = joinpath(ZARR_JL_FIXTURES, "array_1d.zarr")
            z = zopen(path)
            @test size(z) == (20,)
            @test z[:] == Int32.(0:19)
        end

        @testset "group hierarchy" begin
            path = joinpath(ZARR_JL_FIXTURES, "group.zarr")
            g = zopen(path)
            @test g isa ZarrsGroup
            child_keys = keys(g)
            @test "temperature" in child_keys
            temp = g["temperature"]
            @test size(temp) == (10, 10)
            @test temp[:, :] ≈ Float32.(reshape(0:99, 10, 10))
        end
    end
end
