# Cross-language compatibility: Zarrs.jl write → reopen, and read zarrs Rust fixtures
#
# This test validates that Zarrs.jl-generated data can be read back correctly,
# and also reads pre-existing fixtures from the zarrs Rust test suite if available.

using Test
using Zarrs

const ZARRS_JL_FIXTURES = joinpath(@__DIR__, "fixtures", "v3_zarrs_jl")

# Reference data (must match generate_zarrs_jl.jl)
const REF_F32 = Float32.(reshape(0:99, 10, 10))
const REF_I32_1D = Int32.(0:19)
const REF_F64_3D = Float64.(reshape(0:59, 3, 4, 5))

@testset "Zarrs.jl self-compatibility" begin
    if !isdir(ZARRS_JL_FIXTURES)
        @warn "Zarrs.jl fixtures not found at $ZARRS_JL_FIXTURES — run: julia --project test/fixtures/generate_zarrs_jl.jl"
        @test_skip true
    else
        @testset "compressor: $name" for name in ["none", "zstd", "gzip", "blosc"]
            path = joinpath(ZARRS_JL_FIXTURES, "array_$(name).zarr")
            z = zopen(path)
            @test size(z) == (10, 10)
            @test eltype(z) == Float32
            @test z[:, :] ≈ REF_F32
        end

        @testset "dtype: $name" for (name, T, ref_data) in [
            ("bool",       Bool,       Bool[true false; false true]),
            ("int8",       Int8,       Int8.(reshape(0:3, 2, 2))),
            ("int16",      Int16,      Int16.(reshape(0:3, 2, 2))),
            ("int32",      Int32,      Int32.(reshape(0:3, 2, 2))),
            ("int64",      Int64,      Int64.(reshape(0:3, 2, 2))),
            ("uint8",      UInt8,      UInt8.(reshape(0:3, 2, 2))),
            ("uint16",     UInt16,     UInt16.(reshape(0:3, 2, 2))),
            ("uint32",     UInt32,     UInt32.(reshape(0:3, 2, 2))),
            ("uint64",     UInt64,     UInt64.(reshape(0:3, 2, 2))),
            ("float32",    Float32,    Float32[1.5 2.5; 3.5 4.5]),
            ("float64",    Float64,    Float64[1.5 2.5; 3.5 4.5]),
            ("complex64",  ComplexF32, ComplexF32[1+2im 3+4im; 5+6im 7+8im]),
            ("complex128", ComplexF64, ComplexF64[1+2im 3+4im; 5+6im 7+8im]),
        ]
            path = joinpath(ZARRS_JL_FIXTURES, "dtype_$(name).zarr")
            z = zopen(path)
            @test eltype(z) == T
            result = z[ntuple(_ -> Colon(), ndims(z))...]
            @test result == ref_data
        end

        @testset "1D array" begin
            z = zopen(joinpath(ZARRS_JL_FIXTURES, "array_1d.zarr"))
            @test size(z) == (20,)
            @test z[:] == REF_I32_1D
        end

        @testset "3D array" begin
            z = zopen(joinpath(ZARRS_JL_FIXTURES, "array_3d.zarr"))
            @test size(z) == (3, 4, 5)
            @test z[:, :, :] ≈ REF_F64_3D
        end

        @testset "sharded array" begin
            z = zopen(joinpath(ZARRS_JL_FIXTURES, "array_sharded.zarr"))
            @test size(z) == (10, 10)
            @test z[:, :] ≈ REF_F32
        end

        @testset "attributes" begin
            z = zopen(joinpath(ZARRS_JL_FIXTURES, "array_attrs.zarr"))
            attrs = get_attributes(z)
            @test attrs["units"] == "kelvin"
            @test attrs["long_name"] == "temperature"
        end

        @testset "dimension names" begin
            z = zopen(joinpath(ZARRS_JL_FIXTURES, "array_dimnames.zarr"))
            meta_str = Zarrs.LibZarrs.zarrs_array_get_metadata_string(z.handle.ptr)
            meta = Zarrs.JSON.parse(meta_str)
            dim_names = get(meta, "dimension_names", nothing)
            @test dim_names !== nothing
            @test "x" in dim_names
            @test "y" in dim_names
        end
    end
end

# ---------------------------------------------------------------------------
# Read fixtures from the zarrs Rust test suite (if the workspace is available)
# ---------------------------------------------------------------------------
const ZARRS_RUST_FIXTURES = joinpath(@__DIR__, "..", "..", "zarrs", "zarrs", "tests", "data", "v3_zarr_python")

@testset "zarrs Rust V3 test fixtures" begin
    if !isdir(ZARRS_RUST_FIXTURES)
        @info "zarrs Rust fixtures not found at $ZARRS_RUST_FIXTURES — skipping"
        @test_skip true
    else
        # These fixtures are generated by zarrs/zarrs/tests/data/v3_generate.py
        # They contain 10x10 float32 arrays with data 0..99
        expected = Float32.(reshape(0:99, 10, 10))

        @testset "array_$name" for name in ["none", "zstd", "gzip", "blosc"]
            path = joinpath(ZARRS_RUST_FIXTURES, "array_$(name).zarr")
            if !isdir(path)
                @test_skip "fixture not found"
                continue
            end
            z = zopen(path)
            @test size(z) == (10, 10)
            @test eltype(z) == Float32
            @test z[:, :] ≈ expected
        end
    end
end
