# Cross-language compatibility: read fixtures generated by Zarr.jl
#
# This test validates that Zarrs.jl can read arrays written by Zarr.jl.
# Zarr.jl is not a dependency — fixtures must be pre-generated.
# Generate fixtures:  julia --project=../Zarr.jl test/fixtures/generate_zarr_jl.jl
# (or manually create V2 zarr arrays using Zarr.jl)

using Test
using Zarrs

const ZARR_JL_FIXTURES = joinpath(@__DIR__, "fixtures", "v2_zarr_jl")

@testset "Zarr.jl V2 compatibility" begin
    if !isdir(ZARR_JL_FIXTURES)
        @info "Zarr.jl fixtures not found at $ZARR_JL_FIXTURES — skipping"
        @test_skip true
    else
        @testset "read array: $name" for name in readdir(ZARR_JL_FIXTURES)
            path = joinpath(ZARR_JL_FIXTURES, name)
            isdir(path) || continue
            endswith(name, ".zarr") || continue

            z = zopen(path)
            @test size(z) != ()
            # Basic smoke test: can read without error
            data = z[ntuple(_ -> Colon(), ndims(z))...]
            @test length(data) > 0
        end
    end
end
