# This file is automatically generated by gen/generator.jl — DO NOT EDIT.
#
# To regenerate:
#   cd gen/
#   julia --project -e 'using Pkg; Pkg.instantiate()'
#   julia --project generator.jl

module API

# Library path — must be a plain String for ccall((:sym, lib), ...) to work.
# Initialized in __init__() and accessed by all generated ccall wrappers.
libzarrs_jl::String = ""

function __init__()
    global libzarrs_jl = joinpath(
        @__DIR__,
        "..",
        "deps",
        "lib",
        Sys.iswindows() ? "zarrs_jl.dll" :
        Sys.isapple() ? "libzarrs_jl.dylib" : "libzarrs_jl.so",
    )
    if !isfile(libzarrs_jl)
        error(
            "zarrs_jl shared library not found at $(libzarrs_jl). Run `julia deps/build.jl` first.",
        )
    end
end

# ---------------------------------------------------------------------------
# ZarrsResult enum — defined manually because cbindgen emits both
# `enum ZarrsResult { ... }` and `typedef int32_t ZarrsResult` which
# Clang.jl rejects as a duplicate name.
# ---------------------------------------------------------------------------

@enum ZarrsResult::Cint begin
    ZARRS_SUCCESS = 0
    ZARRS_ERROR_NULL_PTR = -1
    ZARRS_ERROR_STORAGE = -2
    ZARRS_ERROR_ARRAY = -3
    ZARRS_ERROR_BUFFER_LENGTH = -4
    ZARRS_ERROR_INVALID_INDICES = -5
    ZARRS_ERROR_NODE_PATH = -6
    ZARRS_ERROR_STORE_PREFIX = -7
    ZARRS_ERROR_INVALID_METADATA = -8
    ZARRS_ERROR_STORAGE_CAPABILITY = -9
    ZARRS_ERROR_UNKNOWN_CHUNK_GRID_SHAPE = -10
    ZARRS_ERROR_UNKNOWN_INTERSECTING_CHUNKS = -11
    ZARRS_ERROR_UNSUPPORTED_DATA_TYPE = -12
    ZARRS_ERROR_GROUP = -13
    ZARRS_ERROR_INCOMPATIBLE_DIMENSIONALITY = -14
end

# ---------------------------------------------------------------------------
# Error handling
# ---------------------------------------------------------------------------

function check_error(result::ZarrsResult)
    result == ZARRS_SUCCESS && return
    msg_ptr = ccall((:zarrsLastError, libzarrs_jl), Ptr{UInt8}, ())
    msg = msg_ptr != C_NULL ? unsafe_string(msg_ptr) : "Unknown zarrs error"
    if msg_ptr != C_NULL
        ccall((:zarrsFreeString, libzarrs_jl), Cvoid, (Ptr{UInt8},), msg_ptr)
    end
    error("zarrs error ($result): $msg")
end

# ---------------------------------------------------------------------------
# Generated bindings
# ---------------------------------------------------------------------------

const StorageHandle = Cvoid

const ArrayHandle = Cvoid

const GroupHandle = Cvoid

const IcStorageHandle = Cvoid

const IcRepoHandle = Cvoid

const IcSessionHandle = Cvoid

"""
    zarrs_last_error()

### Prototype
```c
char *zarrsLastError(void);
```
"""
function zarrs_last_error()
    ptr = ccall((:zarrsLastError, libzarrs_jl), Ptr{UInt8}, ())
    ptr == C_NULL && return nothing
    s = unsafe_string(ptr)
    ccall((:zarrsFreeString, libzarrs_jl), Cvoid, (Ptr{UInt8},), ptr)
    return s
end

"""
    zarrs_free_string(s)

### Prototype
```c
void zarrsFreeString(char *s);
```
"""
function zarrs_free_string(s)
    ccall((:zarrsFreeString, libzarrs_jl), Cvoid, (Cstring,), s)
end

"""
    zarrs_version()

### Prototype
```c
char *zarrsVersion(void);
```
"""
function zarrs_version()
    ptr = ccall((:zarrsVersion, libzarrs_jl), Ptr{UInt8}, ())
    ptr == C_NULL && return nothing
    s = unsafe_string(ptr)
    ccall((:zarrsFreeString, libzarrs_jl), Cvoid, (Ptr{UInt8},), ptr)
    return s
end

"""
    zarrs_create_storage_filesystem(path)

### Prototype
```c
ZarrsResult zarrsCreateStorageFilesystem(const char *path, StorageHandle **pStorage);
```
"""
function zarrs_create_storage_filesystem(path)
    _handle_ptr = Ref{Ptr{Cvoid}}(C_NULL)
    _result = ccall(
        (:zarrsCreateStorageFilesystem, libzarrs_jl),
        ZarrsResult,
        (Cstring, Ptr{Ptr{StorageHandle}}),
        path,
        _handle_ptr,
    )
    check_error(_result)
    return _handle_ptr[]
end

"""
    zarrs_create_storage_http(url)

### Prototype
```c
ZarrsResult zarrsCreateStorageHTTP(const char *url, StorageHandle **pStorage);
```
"""
function zarrs_create_storage_http(url)
    _handle_ptr = Ref{Ptr{Cvoid}}(C_NULL)
    _result = ccall(
        (:zarrsCreateStorageHTTP, libzarrs_jl),
        ZarrsResult,
        (Cstring, Ptr{Ptr{StorageHandle}}),
        url,
        _handle_ptr,
    )
    check_error(_result)
    return _handle_ptr[]
end

"""
    zarrs_create_storage_s3(bucket, prefix, region, endpoint_url, anonymous)

### Prototype
```c
ZarrsResult zarrsCreateStorageS3(const char *bucket, const char *prefix, const char *region, const char *endpoint_url, int32_t anonymous, StorageHandle **pStorage);
```
"""
function zarrs_create_storage_s3(bucket, prefix, region, endpoint_url, anonymous)
    _handle_ptr = Ref{Ptr{Cvoid}}(C_NULL)
    _result = ccall(
        (:zarrsCreateStorageS3, libzarrs_jl),
        ZarrsResult,
        (Cstring, Cstring, Cstring, Cstring, Int32, Ptr{Ptr{StorageHandle}}),
        bucket,
        prefix,
        region,
        endpoint_url,
        anonymous,
        _handle_ptr,
    )
    check_error(_result)
    return _handle_ptr[]
end

"""
    zarrs_create_storage_gcs(bucket, prefix, anonymous)

### Prototype
```c
ZarrsResult zarrsCreateStorageGCS(const char *bucket, const char *prefix, int32_t anonymous, StorageHandle **pStorage);
```
"""
function zarrs_create_storage_gcs(bucket, prefix, anonymous)
    _handle_ptr = Ref{Ptr{Cvoid}}(C_NULL)
    _result = ccall(
        (:zarrsCreateStorageGCS, libzarrs_jl),
        ZarrsResult,
        (Cstring, Cstring, Int32, Ptr{Ptr{StorageHandle}}),
        bucket,
        prefix,
        anonymous,
        _handle_ptr,
    )
    check_error(_result)
    return _handle_ptr[]
end

"""
    zarrs_destroy_storage(storage)

### Prototype
```c
ZarrsResult zarrsDestroyStorage(StorageHandle *storage);
```
"""
function zarrs_destroy_storage(storage)
    _result = ccall(
        (:zarrsDestroyStorage, libzarrs_jl),
        ZarrsResult,
        (Ptr{StorageHandle},),
        storage,
    )
    check_error(_result)
end

"""
    zarrs_create_array_rw(storage, path, metadata_json)

### Prototype
```c
ZarrsResult zarrsCreateArrayRW(StorageHandle *storage, const char *path, const char *metadata_json, ArrayHandle **pArray);
```
"""
function zarrs_create_array_rw(storage, path, metadata_json)
    _handle_ptr = Ref{Ptr{Cvoid}}(C_NULL)
    _result = ccall(
        (:zarrsCreateArrayRW, libzarrs_jl),
        ZarrsResult,
        (Ptr{StorageHandle}, Cstring, Cstring, Ptr{Ptr{ArrayHandle}}),
        storage,
        path,
        metadata_json,
        _handle_ptr,
    )
    check_error(_result)
    return _handle_ptr[]
end

"""
    zarrs_open_array_rw(storage, path)

### Prototype
```c
ZarrsResult zarrsOpenArrayRW(StorageHandle *storage, const char *path, ArrayHandle **pArray);
```
"""
function zarrs_open_array_rw(storage, path)
    _handle_ptr = Ref{Ptr{Cvoid}}(C_NULL)
    _result = ccall(
        (:zarrsOpenArrayRW, libzarrs_jl),
        ZarrsResult,
        (Ptr{StorageHandle}, Cstring, Ptr{Ptr{ArrayHandle}}),
        storage,
        path,
        _handle_ptr,
    )
    check_error(_result)
    return _handle_ptr[]
end

"""
    zarrs_destroy_array(array)

### Prototype
```c
ZarrsResult zarrsDestroyArray(ArrayHandle *array);
```
"""
function zarrs_destroy_array(array)
    _result =
        ccall((:zarrsDestroyArray, libzarrs_jl), ZarrsResult, (Ptr{ArrayHandle},), array)
    check_error(_result)
end

"""
    zarrs_array_get_dimensionality(array)

### Prototype
```c
ZarrsResult zarrsArrayGetDimensionality(ArrayHandle *array, uintptr_t *pDimensionality);
```
"""
function zarrs_array_get_dimensionality(array)
    _out_ref = Ref{Csize_t}(zero(Csize_t))
    _result = ccall(
        (:zarrsArrayGetDimensionality, libzarrs_jl),
        ZarrsResult,
        (Ptr{ArrayHandle}, Ptr{Csize_t}),
        array,
        _out_ref,
    )
    check_error(_result)
    return _out_ref[]
end

"""
    zarrs_array_get_shape(array, dimensionality, pShape)

### Prototype
```c
ZarrsResult zarrsArrayGetShape(ArrayHandle *array, uintptr_t dimensionality, uint64_t *pShape);
```
"""
function zarrs_array_get_shape(array, dimensionality, pShape)
    _result = ccall(
        (:zarrsArrayGetShape, libzarrs_jl),
        ZarrsResult,
        (Ptr{ArrayHandle}, Csize_t, Ptr{UInt64}),
        array,
        dimensionality,
        pShape,
    )
    check_error(_result)
end

"""
    zarrs_array_get_data_type(array)

### Prototype
```c
ZarrsResult zarrsArrayGetDataType(ArrayHandle *array, int32_t *pDataType);
```
"""
function zarrs_array_get_data_type(array)
    _out_ref = Ref{Int32}(zero(Int32))
    _result = ccall(
        (:zarrsArrayGetDataType, libzarrs_jl),
        ZarrsResult,
        (Ptr{ArrayHandle}, Ptr{Int32}),
        array,
        _out_ref,
    )
    check_error(_result)
    return _out_ref[]
end

"""
    zarrs_array_get_metadata_string(array, pretty)

### Prototype
```c
ZarrsResult zarrsArrayGetMetadataString(ArrayHandle *array, int32_t pretty, char **pMetadata);
```
"""
function zarrs_array_get_metadata_string(array, pretty)
    _str_ptr = Ref{Cstring}(C_NULL)
    _result = ccall(
        (:zarrsArrayGetMetadataString, libzarrs_jl),
        ZarrsResult,
        (Ptr{ArrayHandle}, Int32, Ptr{Cstring}),
        array,
        pretty,
        _str_ptr,
    )
    check_error(_result)
    if _str_ptr[] == C_NULL
        return nothing
    end
    _s = unsafe_string(_str_ptr[])
    ccall((:zarrsFreeString, libzarrs_jl), Cvoid, (Cstring,), _str_ptr[])
    return _s
end

"""
    zarrs_array_get_attributes(array, pretty)

### Prototype
```c
ZarrsResult zarrsArrayGetAttributes(ArrayHandle *array, int32_t pretty, char **pAttributes);
```
"""
function zarrs_array_get_attributes(array, pretty)
    _str_ptr = Ref{Cstring}(C_NULL)
    _result = ccall(
        (:zarrsArrayGetAttributes, libzarrs_jl),
        ZarrsResult,
        (Ptr{ArrayHandle}, Int32, Ptr{Cstring}),
        array,
        pretty,
        _str_ptr,
    )
    check_error(_result)
    if _str_ptr[] == C_NULL
        return nothing
    end
    _s = unsafe_string(_str_ptr[])
    ccall((:zarrsFreeString, libzarrs_jl), Cvoid, (Cstring,), _str_ptr[])
    return _s
end

"""
    zarrs_array_set_attributes(array, attributes)

### Prototype
```c
ZarrsResult zarrsArraySetAttributes(ArrayHandle *array, const char *attributes);
```
"""
function zarrs_array_set_attributes(array, attributes)
    _result = ccall(
        (:zarrsArraySetAttributes, libzarrs_jl),
        ZarrsResult,
        (Ptr{ArrayHandle}, Cstring),
        array,
        attributes,
    )
    check_error(_result)
end

"""
    zarrs_array_store_metadata(array)

### Prototype
```c
ZarrsResult zarrsArrayStoreMetadata(ArrayHandle *array);
```
"""
function zarrs_array_store_metadata(array)
    _result = ccall(
        (:zarrsArrayStoreMetadata, libzarrs_jl),
        ZarrsResult,
        (Ptr{ArrayHandle},),
        array,
    )
    check_error(_result)
end

"""
    zarrs_array_get_subset_size(array, dimensionality, pSubsetShape)

### Prototype
```c
ZarrsResult zarrsArrayGetSubsetSize(ArrayHandle *array, uintptr_t dimensionality, const uint64_t *pSubsetShape, uintptr_t *pSubsetSize);
```
"""
function zarrs_array_get_subset_size(array, dimensionality, pSubsetShape)
    _out_ref = Ref{Csize_t}(zero(Csize_t))
    _result = ccall(
        (:zarrsArrayGetSubsetSize, libzarrs_jl),
        ZarrsResult,
        (Ptr{ArrayHandle}, Csize_t, Ptr{UInt64}, Ptr{Csize_t}),
        array,
        dimensionality,
        pSubsetShape,
        _out_ref,
    )
    check_error(_result)
    return _out_ref[]
end

"""
    zarrs_array_retrieve_subset(array, dimensionality, pSubsetStart, pSubsetShape, subsetBytesCount, pSubsetBytes)

### Prototype
```c
ZarrsResult zarrsArrayRetrieveSubset(ArrayHandle *array, uintptr_t dimensionality, const uint64_t *pSubsetStart, const uint64_t *pSubsetShape, uintptr_t subsetBytesCount, uint8_t *pSubsetBytes);
```
"""
function zarrs_array_retrieve_subset(
    array,
    dimensionality,
    pSubsetStart,
    pSubsetShape,
    subsetBytesCount,
    pSubsetBytes,
)
    _result = ccall(
        (:zarrsArrayRetrieveSubset, libzarrs_jl),
        ZarrsResult,
        (Ptr{ArrayHandle}, Csize_t, Ptr{UInt64}, Ptr{UInt64}, Csize_t, Ptr{UInt8}),
        array,
        dimensionality,
        pSubsetStart,
        pSubsetShape,
        subsetBytesCount,
        pSubsetBytes,
    )
    check_error(_result)
end

"""
    zarrs_array_store_subset(array, dimensionality, pSubsetStart, pSubsetShape, subsetBytesCount, pSubsetBytes)

### Prototype
```c
ZarrsResult zarrsArrayStoreSubset(ArrayHandle *array, uintptr_t dimensionality, const uint64_t *pSubsetStart, const uint64_t *pSubsetShape, uintptr_t subsetBytesCount, const uint8_t *pSubsetBytes);
```
"""
function zarrs_array_store_subset(
    array,
    dimensionality,
    pSubsetStart,
    pSubsetShape,
    subsetBytesCount,
    pSubsetBytes,
)
    _result = ccall(
        (:zarrsArrayStoreSubset, libzarrs_jl),
        ZarrsResult,
        (Ptr{ArrayHandle}, Csize_t, Ptr{UInt64}, Ptr{UInt64}, Csize_t, Ptr{UInt8}),
        array,
        dimensionality,
        pSubsetStart,
        pSubsetShape,
        subsetBytesCount,
        pSubsetBytes,
    )
    check_error(_result)
end

"""
    zarrs_array_get_chunk_grid_shape(array, dimensionality, pChunkGridShape)

### Prototype
```c
ZarrsResult zarrsArrayGetChunkGridShape(ArrayHandle *array, uintptr_t dimensionality, uint64_t *pChunkGridShape);
```
"""
function zarrs_array_get_chunk_grid_shape(array, dimensionality, pChunkGridShape)
    _result = ccall(
        (:zarrsArrayGetChunkGridShape, libzarrs_jl),
        ZarrsResult,
        (Ptr{ArrayHandle}, Csize_t, Ptr{UInt64}),
        array,
        dimensionality,
        pChunkGridShape,
    )
    check_error(_result)
end

"""
    zarrs_array_get_chunk_size(array, dimensionality, pChunkIndices)

### Prototype
```c
ZarrsResult zarrsArrayGetChunkSize(ArrayHandle *array, uintptr_t dimensionality, const uint64_t *pChunkIndices, uintptr_t *pChunkSize);
```
"""
function zarrs_array_get_chunk_size(array, dimensionality, pChunkIndices)
    _out_ref = Ref{Csize_t}(zero(Csize_t))
    _result = ccall(
        (:zarrsArrayGetChunkSize, libzarrs_jl),
        ZarrsResult,
        (Ptr{ArrayHandle}, Csize_t, Ptr{UInt64}, Ptr{Csize_t}),
        array,
        dimensionality,
        pChunkIndices,
        _out_ref,
    )
    check_error(_result)
    return _out_ref[]
end

"""
    zarrs_array_retrieve_chunk(array, dimensionality, pChunkIndices, chunkBytesCount, pChunkBytes)

### Prototype
```c
ZarrsResult zarrsArrayRetrieveChunk(ArrayHandle *array, uintptr_t dimensionality, const uint64_t *pChunkIndices, uintptr_t chunkBytesCount, uint8_t *pChunkBytes);
```
"""
function zarrs_array_retrieve_chunk(
    array,
    dimensionality,
    pChunkIndices,
    chunkBytesCount,
    pChunkBytes,
)
    _result = ccall(
        (:zarrsArrayRetrieveChunk, libzarrs_jl),
        ZarrsResult,
        (Ptr{ArrayHandle}, Csize_t, Ptr{UInt64}, Csize_t, Ptr{UInt8}),
        array,
        dimensionality,
        pChunkIndices,
        chunkBytesCount,
        pChunkBytes,
    )
    check_error(_result)
end

"""
    zarrs_array_store_chunk(array, dimensionality, pChunkIndices, chunkBytesCount, pChunkBytes)

### Prototype
```c
ZarrsResult zarrsArrayStoreChunk(ArrayHandle *array, uintptr_t dimensionality, const uint64_t *pChunkIndices, uintptr_t chunkBytesCount, const uint8_t *pChunkBytes);
```
"""
function zarrs_array_store_chunk(
    array,
    dimensionality,
    pChunkIndices,
    chunkBytesCount,
    pChunkBytes,
)
    _result = ccall(
        (:zarrsArrayStoreChunk, libzarrs_jl),
        ZarrsResult,
        (Ptr{ArrayHandle}, Csize_t, Ptr{UInt64}, Csize_t, Ptr{UInt8}),
        array,
        dimensionality,
        pChunkIndices,
        chunkBytesCount,
        pChunkBytes,
    )
    check_error(_result)
end

"""
    zarrs_array_get_chunk_origin(array, dimensionality, pChunkIndices, pChunkOrigin)

### Prototype
```c
ZarrsResult zarrsArrayGetChunkOrigin(ArrayHandle *array, uintptr_t dimensionality, const uint64_t *pChunkIndices, uint64_t *pChunkOrigin);
```
"""
function zarrs_array_get_chunk_origin(array, dimensionality, pChunkIndices, pChunkOrigin)
    _result = ccall(
        (:zarrsArrayGetChunkOrigin, libzarrs_jl),
        ZarrsResult,
        (Ptr{ArrayHandle}, Csize_t, Ptr{UInt64}, Ptr{UInt64}),
        array,
        dimensionality,
        pChunkIndices,
        pChunkOrigin,
    )
    check_error(_result)
end

"""
    zarrs_array_get_chunk_shape(array, dimensionality, pChunkIndices, pChunkShape)

### Prototype
```c
ZarrsResult zarrsArrayGetChunkShape(ArrayHandle *array, uintptr_t dimensionality, const uint64_t *pChunkIndices, uint64_t *pChunkShape);
```
"""
function zarrs_array_get_chunk_shape(array, dimensionality, pChunkIndices, pChunkShape)
    _result = ccall(
        (:zarrsArrayGetChunkShape, libzarrs_jl),
        ZarrsResult,
        (Ptr{ArrayHandle}, Csize_t, Ptr{UInt64}, Ptr{UInt64}),
        array,
        dimensionality,
        pChunkIndices,
        pChunkShape,
    )
    check_error(_result)
end

"""
    zarrs_array_get_sub_chunk_shape(array, dimensionality, pIsSharded, pSubChunkShape)

### Prototype
```c
ZarrsResult zarrsArrayGetSubChunkShape(ArrayHandle *array, uintptr_t dimensionality, int32_t *pIsSharded, uint64_t *pSubChunkShape);
```
"""
function zarrs_array_get_sub_chunk_shape(array, dimensionality, pIsSharded, pSubChunkShape)
    _result = ccall(
        (:zarrsArrayGetSubChunkShape, libzarrs_jl),
        ZarrsResult,
        (Ptr{ArrayHandle}, Csize_t, Ptr{Int32}, Ptr{UInt64}),
        array,
        dimensionality,
        pIsSharded,
        pSubChunkShape,
    )
    check_error(_result)
end

"""
    zarrs_create_group_rw(storage, path, metadata_json)

### Prototype
```c
ZarrsResult zarrsCreateGroupRW(StorageHandle *storage, const char *path, const char *metadata_json, GroupHandle **pGroup);
```
"""
function zarrs_create_group_rw(storage, path, metadata_json)
    _handle_ptr = Ref{Ptr{Cvoid}}(C_NULL)
    _result = ccall(
        (:zarrsCreateGroupRW, libzarrs_jl),
        ZarrsResult,
        (Ptr{StorageHandle}, Cstring, Cstring, Ptr{Ptr{GroupHandle}}),
        storage,
        path,
        metadata_json,
        _handle_ptr,
    )
    check_error(_result)
    return _handle_ptr[]
end

"""
    zarrs_open_group_rw(storage, path)

### Prototype
```c
ZarrsResult zarrsOpenGroupRW(StorageHandle *storage, const char *path, GroupHandle **pGroup);
```
"""
function zarrs_open_group_rw(storage, path)
    _handle_ptr = Ref{Ptr{Cvoid}}(C_NULL)
    _result = ccall(
        (:zarrsOpenGroupRW, libzarrs_jl),
        ZarrsResult,
        (Ptr{StorageHandle}, Cstring, Ptr{Ptr{GroupHandle}}),
        storage,
        path,
        _handle_ptr,
    )
    check_error(_result)
    return _handle_ptr[]
end

"""
    zarrs_destroy_group(group)

### Prototype
```c
ZarrsResult zarrsDestroyGroup(GroupHandle *group);
```
"""
function zarrs_destroy_group(group)
    _result =
        ccall((:zarrsDestroyGroup, libzarrs_jl), ZarrsResult, (Ptr{GroupHandle},), group)
    check_error(_result)
end

"""
    zarrs_group_get_attributes(group, pretty)

### Prototype
```c
ZarrsResult zarrsGroupGetAttributes(GroupHandle *group, int32_t pretty, char **pAttributes);
```
"""
function zarrs_group_get_attributes(group, pretty)
    _str_ptr = Ref{Cstring}(C_NULL)
    _result = ccall(
        (:zarrsGroupGetAttributes, libzarrs_jl),
        ZarrsResult,
        (Ptr{GroupHandle}, Int32, Ptr{Cstring}),
        group,
        pretty,
        _str_ptr,
    )
    check_error(_result)
    if _str_ptr[] == C_NULL
        return nothing
    end
    _s = unsafe_string(_str_ptr[])
    ccall((:zarrsFreeString, libzarrs_jl), Cvoid, (Cstring,), _str_ptr[])
    return _s
end

"""
    zarrs_group_set_attributes(group, attributes)

### Prototype
```c
ZarrsResult zarrsGroupSetAttributes(GroupHandle *group, const char *attributes);
```
"""
function zarrs_group_set_attributes(group, attributes)
    _result = ccall(
        (:zarrsGroupSetAttributes, libzarrs_jl),
        ZarrsResult,
        (Ptr{GroupHandle}, Cstring),
        group,
        attributes,
    )
    check_error(_result)
end

"""
    zarrs_group_store_metadata(group)

### Prototype
```c
ZarrsResult zarrsGroupStoreMetadata(GroupHandle *group);
```
"""
function zarrs_group_store_metadata(group)
    _result = ccall(
        (:zarrsGroupStoreMetadata, libzarrs_jl),
        ZarrsResult,
        (Ptr{GroupHandle},),
        group,
    )
    check_error(_result)
end

"""
    zarrs_jl_array_resize(storage, path, ndim, new_shape)

Resize an array.

### Prototype
```c
ZarrsResult zarrsJlArrayResize(StorageHandle *storage, const char *path, uintptr_t ndim, const uint64_t *new_shape);
```
"""
function zarrs_jl_array_resize(storage, path, ndim, new_shape)
    _result = ccall(
        (:zarrsJlArrayResize, libzarrs_jl),
        ZarrsResult,
        (Ptr{StorageHandle}, Cstring, Csize_t, Ptr{UInt64}),
        storage,
        path,
        ndim,
        new_shape,
    )
    check_error(_result)
end

"""
    zarrs_jl_storage_list_dir(storage, path)

List directory children, returning a JSON array of strings.

### Prototype
```c
ZarrsResult zarrsJlStorageListDir(StorageHandle *storage, const char *path, char **json_out);
```
"""
function zarrs_jl_storage_list_dir(storage, path)
    _str_ptr = Ref{Cstring}(C_NULL)
    _result = ccall(
        (:zarrsJlStorageListDir, libzarrs_jl),
        ZarrsResult,
        (Ptr{StorageHandle}, Cstring, Ptr{Cstring}),
        storage,
        path,
        _str_ptr,
    )
    check_error(_result)
    if _str_ptr[] == C_NULL
        return nothing
    end
    _s = unsafe_string(_str_ptr[])
    ccall((:zarrsFreeString, libzarrs_jl), Cvoid, (Cstring,), _str_ptr[])
    return _s
end

"""
    zarrs_jl_storage_get(storage, key)

Read a single key from storage, returning its bytes as a C string. Returns ZARRS\\_SUCCESS with null output if the key is not found.

### Prototype
```c
ZarrsResult zarrsJlStorageGet(StorageHandle *storage, const char *key, char **data_out);
```
"""
function zarrs_jl_storage_get(storage, key)
    _str_ptr = Ref{Cstring}(C_NULL)
    _result = ccall(
        (:zarrsJlStorageGet, libzarrs_jl),
        ZarrsResult,
        (Ptr{StorageHandle}, Cstring, Ptr{Cstring}),
        storage,
        key,
        _str_ptr,
    )
    check_error(_result)
    if _str_ptr[] == C_NULL
        return nothing
    end
    _s = unsafe_string(_str_ptr[])
    ccall((:zarrsFreeString, libzarrs_jl), Cvoid, (Cstring,), _str_ptr[])
    return _s
end

"""
    zarrs_jl_array_erase_chunk(storage, path, ndim, indices)

Erase a specific chunk from an array.

### Prototype
```c
ZarrsResult zarrsJlArrayEraseChunk(StorageHandle *storage, const char *path, uintptr_t ndim, const uint64_t *indices);
```
"""
function zarrs_jl_array_erase_chunk(storage, path, ndim, indices)
    _result = ccall(
        (:zarrsJlArrayEraseChunk, libzarrs_jl),
        ZarrsResult,
        (Ptr{StorageHandle}, Cstring, Csize_t, Ptr{UInt64}),
        storage,
        path,
        ndim,
        indices,
    )
    check_error(_result)
end

"""
    zarrs_icechunk_s3_storage(bucket, prefix, region, anonymous, endpoint_url, allow_http, access_key_id, secret_access_key, session_token)

### Prototype
```c
ZarrsResult zarrsIcechunkS3Storage(const char *bucket, const char *prefix, const char *region, int32_t anonymous, const char *endpoint_url, int32_t allow_http, const char *access_key_id, const char *secret_access_key, const char *session_token, IcStorageHandle **pHandle);
```
"""
function zarrs_icechunk_s3_storage(
    bucket,
    prefix,
    region,
    anonymous,
    endpoint_url,
    allow_http,
    access_key_id,
    secret_access_key,
    session_token,
)
    _handle_ptr = Ref{Ptr{Cvoid}}(C_NULL)
    _result = ccall(
        (:zarrsIcechunkS3Storage, libzarrs_jl),
        ZarrsResult,
        (
            Cstring,
            Cstring,
            Cstring,
            Int32,
            Cstring,
            Int32,
            Cstring,
            Cstring,
            Cstring,
            Ptr{Ptr{IcStorageHandle}},
        ),
        bucket,
        prefix,
        region,
        anonymous,
        endpoint_url,
        allow_http,
        access_key_id,
        secret_access_key,
        session_token,
        _handle_ptr,
    )
    check_error(_result)
    return _handle_ptr[]
end

"""
    zarrs_icechunk_gcs_storage(bucket, prefix, credential_type, credential_value)

### Prototype
```c
ZarrsResult zarrsIcechunkGcsStorage(const char *bucket, const char *prefix, int32_t credential_type, const char *credential_value, IcStorageHandle **pHandle);
```
"""
function zarrs_icechunk_gcs_storage(bucket, prefix, credential_type, credential_value)
    _handle_ptr = Ref{Ptr{Cvoid}}(C_NULL)
    _result = ccall(
        (:zarrsIcechunkGcsStorage, libzarrs_jl),
        ZarrsResult,
        (Cstring, Cstring, Int32, Cstring, Ptr{Ptr{IcStorageHandle}}),
        bucket,
        prefix,
        credential_type,
        credential_value,
        _handle_ptr,
    )
    check_error(_result)
    return _handle_ptr[]
end

"""
    zarrs_icechunk_azure_storage(account, container, prefix, credential_type, credential_value)

### Prototype
```c
ZarrsResult zarrsIcechunkAzureStorage(const char *account, const char *container, const char *prefix, int32_t credential_type, const char *credential_value, IcStorageHandle **pHandle);
```
"""
function zarrs_icechunk_azure_storage(
    account,
    container,
    prefix,
    credential_type,
    credential_value,
)
    _handle_ptr = Ref{Ptr{Cvoid}}(C_NULL)
    _result = ccall(
        (:zarrsIcechunkAzureStorage, libzarrs_jl),
        ZarrsResult,
        (Cstring, Cstring, Cstring, Int32, Cstring, Ptr{Ptr{IcStorageHandle}}),
        account,
        container,
        prefix,
        credential_type,
        credential_value,
        _handle_ptr,
    )
    check_error(_result)
    return _handle_ptr[]
end

"""
    zarrs_icechunk_local_storage(path)

### Prototype
```c
ZarrsResult zarrsIcechunkLocalStorage(const char *path, IcStorageHandle **pHandle);
```
"""
function zarrs_icechunk_local_storage(path)
    _handle_ptr = Ref{Ptr{Cvoid}}(C_NULL)
    _result = ccall(
        (:zarrsIcechunkLocalStorage, libzarrs_jl),
        ZarrsResult,
        (Cstring, Ptr{Ptr{IcStorageHandle}}),
        path,
        _handle_ptr,
    )
    check_error(_result)
    return _handle_ptr[]
end

"""
    zarrs_icechunk_memory_storage()

### Prototype
```c
ZarrsResult zarrsIcechunkMemoryStorage(IcStorageHandle **pHandle);
```
"""
function zarrs_icechunk_memory_storage()
    _handle_ptr = Ref{Ptr{Cvoid}}(C_NULL)
    _result = ccall(
        (:zarrsIcechunkMemoryStorage, libzarrs_jl),
        ZarrsResult,
        (Ptr{Ptr{IcStorageHandle}},),
        _handle_ptr,
    )
    check_error(_result)
    return _handle_ptr[]
end

"""
    zarrs_icechunk_destroy_storage(handle)

### Prototype
```c
ZarrsResult zarrsIcechunkDestroyStorage(IcStorageHandle *handle);
```
"""
function zarrs_icechunk_destroy_storage(handle)
    _result = ccall(
        (:zarrsIcechunkDestroyStorage, libzarrs_jl),
        ZarrsResult,
        (Ptr{IcStorageHandle},),
        handle,
    )
    check_error(_result)
end

"""
    zarrs_icechunk_repo_open(ic_storage)

### Prototype
```c
ZarrsResult zarrsIcechunkRepoOpen(IcStorageHandle *ic_storage, IcRepoHandle **pRepo);
```
"""
function zarrs_icechunk_repo_open(ic_storage)
    _handle_ptr = Ref{Ptr{Cvoid}}(C_NULL)
    _result = ccall(
        (:zarrsIcechunkRepoOpen, libzarrs_jl),
        ZarrsResult,
        (Ptr{IcStorageHandle}, Ptr{Ptr{IcRepoHandle}}),
        ic_storage,
        _handle_ptr,
    )
    check_error(_result)
    return _handle_ptr[]
end

"""
    zarrs_icechunk_repo_create(ic_storage)

### Prototype
```c
ZarrsResult zarrsIcechunkRepoCreate(IcStorageHandle *ic_storage, IcRepoHandle **pRepo);
```
"""
function zarrs_icechunk_repo_create(ic_storage)
    _handle_ptr = Ref{Ptr{Cvoid}}(C_NULL)
    _result = ccall(
        (:zarrsIcechunkRepoCreate, libzarrs_jl),
        ZarrsResult,
        (Ptr{IcStorageHandle}, Ptr{Ptr{IcRepoHandle}}),
        ic_storage,
        _handle_ptr,
    )
    check_error(_result)
    return _handle_ptr[]
end

"""
    zarrs_icechunk_repo_open_or_create(ic_storage)

### Prototype
```c
ZarrsResult zarrsIcechunkRepoOpenOrCreate(IcStorageHandle *ic_storage, IcRepoHandle **pRepo);
```
"""
function zarrs_icechunk_repo_open_or_create(ic_storage)
    _handle_ptr = Ref{Ptr{Cvoid}}(C_NULL)
    _result = ccall(
        (:zarrsIcechunkRepoOpenOrCreate, libzarrs_jl),
        ZarrsResult,
        (Ptr{IcStorageHandle}, Ptr{Ptr{IcRepoHandle}}),
        ic_storage,
        _handle_ptr,
    )
    check_error(_result)
    return _handle_ptr[]
end

"""
    zarrs_icechunk_destroy_repo(repo)

### Prototype
```c
ZarrsResult zarrsIcechunkDestroyRepo(IcRepoHandle *repo);
```
"""
function zarrs_icechunk_destroy_repo(repo)
    _result = ccall(
        (:zarrsIcechunkDestroyRepo, libzarrs_jl),
        ZarrsResult,
        (Ptr{IcRepoHandle},),
        repo,
    )
    check_error(_result)
end

"""
    zarrs_icechunk_repo_list_branches(repo)

### Prototype
```c
ZarrsResult zarrsIcechunkRepoListBranches(IcRepoHandle *repo, char **pJson);
```
"""
function zarrs_icechunk_repo_list_branches(repo)
    _str_ptr = Ref{Cstring}(C_NULL)
    _result = ccall(
        (:zarrsIcechunkRepoListBranches, libzarrs_jl),
        ZarrsResult,
        (Ptr{IcRepoHandle}, Ptr{Cstring}),
        repo,
        _str_ptr,
    )
    check_error(_result)
    if _str_ptr[] == C_NULL
        return nothing
    end
    _s = unsafe_string(_str_ptr[])
    ccall((:zarrsFreeString, libzarrs_jl), Cvoid, (Cstring,), _str_ptr[])
    return _s
end

"""
    zarrs_icechunk_repo_list_tags(repo)

### Prototype
```c
ZarrsResult zarrsIcechunkRepoListTags(IcRepoHandle *repo, char **pJson);
```
"""
function zarrs_icechunk_repo_list_tags(repo)
    _str_ptr = Ref{Cstring}(C_NULL)
    _result = ccall(
        (:zarrsIcechunkRepoListTags, libzarrs_jl),
        ZarrsResult,
        (Ptr{IcRepoHandle}, Ptr{Cstring}),
        repo,
        _str_ptr,
    )
    check_error(_result)
    if _str_ptr[] == C_NULL
        return nothing
    end
    _s = unsafe_string(_str_ptr[])
    ccall((:zarrsFreeString, libzarrs_jl), Cvoid, (Cstring,), _str_ptr[])
    return _s
end

"""
    zarrs_icechunk_repo_create_branch(repo, name, snapshot_id_str)

### Prototype
```c
ZarrsResult zarrsIcechunkRepoCreateBranch(IcRepoHandle *repo, const char *name, const char *snapshot_id_str, char **pResult);
```
"""
function zarrs_icechunk_repo_create_branch(repo, name, snapshot_id_str)
    _str_ptr = Ref{Cstring}(C_NULL)
    _result = ccall(
        (:zarrsIcechunkRepoCreateBranch, libzarrs_jl),
        ZarrsResult,
        (Ptr{IcRepoHandle}, Cstring, Cstring, Ptr{Cstring}),
        repo,
        name,
        snapshot_id_str,
        _str_ptr,
    )
    check_error(_result)
    if _str_ptr[] == C_NULL
        return nothing
    end
    _s = unsafe_string(_str_ptr[])
    ccall((:zarrsFreeString, libzarrs_jl), Cvoid, (Cstring,), _str_ptr[])
    return _s
end

"""
    zarrs_icechunk_repo_delete_branch(repo, name)

### Prototype
```c
ZarrsResult zarrsIcechunkRepoDeleteBranch(IcRepoHandle *repo, const char *name);
```
"""
function zarrs_icechunk_repo_delete_branch(repo, name)
    _result = ccall(
        (:zarrsIcechunkRepoDeleteBranch, libzarrs_jl),
        ZarrsResult,
        (Ptr{IcRepoHandle}, Cstring),
        repo,
        name,
    )
    check_error(_result)
end

"""
    zarrs_icechunk_repo_create_tag(repo, name, snapshot_id_str)

### Prototype
```c
ZarrsResult zarrsIcechunkRepoCreateTag(IcRepoHandle *repo, const char *name, const char *snapshot_id_str, char **pResult);
```
"""
function zarrs_icechunk_repo_create_tag(repo, name, snapshot_id_str)
    _str_ptr = Ref{Cstring}(C_NULL)
    _result = ccall(
        (:zarrsIcechunkRepoCreateTag, libzarrs_jl),
        ZarrsResult,
        (Ptr{IcRepoHandle}, Cstring, Cstring, Ptr{Cstring}),
        repo,
        name,
        snapshot_id_str,
        _str_ptr,
    )
    check_error(_result)
    if _str_ptr[] == C_NULL
        return nothing
    end
    _s = unsafe_string(_str_ptr[])
    ccall((:zarrsFreeString, libzarrs_jl), Cvoid, (Cstring,), _str_ptr[])
    return _s
end

"""
    zarrs_icechunk_repo_delete_tag(repo, name)

### Prototype
```c
ZarrsResult zarrsIcechunkRepoDeleteTag(IcRepoHandle *repo, const char *name);
```
"""
function zarrs_icechunk_repo_delete_tag(repo, name)
    _result = ccall(
        (:zarrsIcechunkRepoDeleteTag, libzarrs_jl),
        ZarrsResult,
        (Ptr{IcRepoHandle}, Cstring),
        repo,
        name,
    )
    check_error(_result)
end

"""
    zarrs_icechunk_repo_lookup_branch(repo, name)

### Prototype
```c
ZarrsResult zarrsIcechunkRepoLookupBranch(IcRepoHandle *repo, const char *name, char **pSnapshotId);
```
"""
function zarrs_icechunk_repo_lookup_branch(repo, name)
    _str_ptr = Ref{Cstring}(C_NULL)
    _result = ccall(
        (:zarrsIcechunkRepoLookupBranch, libzarrs_jl),
        ZarrsResult,
        (Ptr{IcRepoHandle}, Cstring, Ptr{Cstring}),
        repo,
        name,
        _str_ptr,
    )
    check_error(_result)
    if _str_ptr[] == C_NULL
        return nothing
    end
    _s = unsafe_string(_str_ptr[])
    ccall((:zarrsFreeString, libzarrs_jl), Cvoid, (Cstring,), _str_ptr[])
    return _s
end

"""
    zarrs_icechunk_repo_lookup_tag(repo, name)

### Prototype
```c
ZarrsResult zarrsIcechunkRepoLookupTag(IcRepoHandle *repo, const char *name, char **pSnapshotId);
```
"""
function zarrs_icechunk_repo_lookup_tag(repo, name)
    _str_ptr = Ref{Cstring}(C_NULL)
    _result = ccall(
        (:zarrsIcechunkRepoLookupTag, libzarrs_jl),
        ZarrsResult,
        (Ptr{IcRepoHandle}, Cstring, Ptr{Cstring}),
        repo,
        name,
        _str_ptr,
    )
    check_error(_result)
    if _str_ptr[] == C_NULL
        return nothing
    end
    _s = unsafe_string(_str_ptr[])
    ccall((:zarrsFreeString, libzarrs_jl), Cvoid, (Cstring,), _str_ptr[])
    return _s
end

"""
    zarrs_icechunk_readonly_session(repo, version_type, version_value)

Create a readonly session. `version_type`: 0 = branch, 1 = tag, 2 = snapshot\\_id `version_value`: the branch name, tag name, or snapshot ID string

### Prototype
```c
ZarrsResult zarrsIcechunkReadonlySession(IcRepoHandle *repo, int32_t version_type, const char *version_value, IcSessionHandle **pSession);
```
"""
function zarrs_icechunk_readonly_session(repo, version_type, version_value)
    _handle_ptr = Ref{Ptr{Cvoid}}(C_NULL)
    _result = ccall(
        (:zarrsIcechunkReadonlySession, libzarrs_jl),
        ZarrsResult,
        (Ptr{IcRepoHandle}, Int32, Cstring, Ptr{Ptr{IcSessionHandle}}),
        repo,
        version_type,
        version_value,
        _handle_ptr,
    )
    check_error(_result)
    return _handle_ptr[]
end

"""
    zarrs_icechunk_writable_session(repo, branch)

Create a writable session on a branch.

### Prototype
```c
ZarrsResult zarrsIcechunkWritableSession(IcRepoHandle *repo, const char *branch, IcSessionHandle **pSession);
```
"""
function zarrs_icechunk_writable_session(repo, branch)
    _handle_ptr = Ref{Ptr{Cvoid}}(C_NULL)
    _result = ccall(
        (:zarrsIcechunkWritableSession, libzarrs_jl),
        ZarrsResult,
        (Ptr{IcRepoHandle}, Cstring, Ptr{Ptr{IcSessionHandle}}),
        repo,
        branch,
        _handle_ptr,
    )
    check_error(_result)
    return _handle_ptr[]
end

"""
    zarrs_icechunk_destroy_session(session)

### Prototype
```c
ZarrsResult zarrsIcechunkDestroySession(IcSessionHandle *session);
```
"""
function zarrs_icechunk_destroy_session(session)
    _result = ccall(
        (:zarrsIcechunkDestroySession, libzarrs_jl),
        ZarrsResult,
        (Ptr{IcSessionHandle},),
        session,
    )
    check_error(_result)
end

"""
    zarrs_icechunk_session_get_storage(session)

Create a zarrs-compatible [`StorageHandle`](@ref) from an Icechunk session. This bridges the Icechunk Store to the zarrs sync storage interface.

### Prototype
```c
ZarrsResult zarrsIcechunkSessionGetStorage(IcSessionHandle *session, StorageHandle **pStorage);
```
"""
function zarrs_icechunk_session_get_storage(session)
    _handle_ptr = Ref{Ptr{Cvoid}}(C_NULL)
    _result = ccall(
        (:zarrsIcechunkSessionGetStorage, libzarrs_jl),
        ZarrsResult,
        (Ptr{IcSessionHandle}, Ptr{Ptr{StorageHandle}}),
        session,
        _handle_ptr,
    )
    check_error(_result)
    return _handle_ptr[]
end

"""
    zarrs_icechunk_session_read_only(session)

Check if a session is read-only.

### Prototype
```c
ZarrsResult zarrsIcechunkSessionReadOnly(IcSessionHandle *session, int32_t *pReadOnly);
```
"""
function zarrs_icechunk_session_read_only(session)
    _out_ref = Ref{Int32}(zero(Int32))
    _result = ccall(
        (:zarrsIcechunkSessionReadOnly, libzarrs_jl),
        ZarrsResult,
        (Ptr{IcSessionHandle}, Ptr{Int32}),
        session,
        _out_ref,
    )
    check_error(_result)
    return _out_ref[]
end

"""
    zarrs_icechunk_session_commit(session, message)

Commit a writable session with a message, returning a snapshot ID string.

### Prototype
```c
ZarrsResult zarrsIcechunkSessionCommit(IcSessionHandle *session, const char *message, char **pSnapshotId);
```
"""
function zarrs_icechunk_session_commit(session, message)
    _str_ptr = Ref{Cstring}(C_NULL)
    _result = ccall(
        (:zarrsIcechunkSessionCommit, libzarrs_jl),
        ZarrsResult,
        (Ptr{IcSessionHandle}, Cstring, Ptr{Cstring}),
        session,
        message,
        _str_ptr,
    )
    check_error(_result)
    if _str_ptr[] == C_NULL
        return nothing
    end
    _s = unsafe_string(_str_ptr[])
    ccall((:zarrsFreeString, libzarrs_jl), Cvoid, (Cstring,), _str_ptr[])
    return _s
end

"""
    zarrs_icechunk_session_has_changes(session)

Check if a session has uncommitted changes.

### Prototype
```c
ZarrsResult zarrsIcechunkSessionHasChanges(IcSessionHandle *session, int32_t *pHasChanges);
```
"""
function zarrs_icechunk_session_has_changes(session)
    _out_ref = Ref{Int32}(zero(Int32))
    _result = ccall(
        (:zarrsIcechunkSessionHasChanges, libzarrs_jl),
        ZarrsResult,
        (Ptr{IcSessionHandle}, Ptr{Int32}),
        session,
        _out_ref,
    )
    check_error(_result)
    return _out_ref[]
end



end # module API
